---
# vim:ft=ansible:
basic_config:
    boot_disk_size: 10GB
    boot_disk_type: pd-standard
    name: tst-nico
    image_family: centos-7
    image_project: centos-cloud
    machine_type: n1-standard-1
    can_ip_forward: --can-ip-forward
    zone: europe-west4-a
    # ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/gcloud.pub"
    instances_count: 4
    tags: http-server,test-nico-netw

inventory_output_file: ./output.ini

instance_admin_group:
  name: nico-admin-group
  project: nicos-101-project
  zone: europe-west4-a
  instances: tst-nico-001,tst-nico-002

instance_db_group:
  name: nico-db-group
  project: nicos-101-project
  zone: europe-west4-a
  instances: tst-nico-003,tst-nico-004

