---
# vim:ft=ansible:
- name: Check if Google Cloud SDK is installed
  command: gcloud version
  register: gcloud_installed
  changed_when: false
  ignore_errors: yes

- fail:
    msg: "Please make sure Google Cloud SDK is installed before executing the role."
  when: gcloud_installed | failed

- name: Check if instances are created
  command: "gcloud compute instances list --filter='name:{{ basic_config.name }}' --format='value(status)'"
  register: instance_created
  changed_when: false
  ignore_errors: yes

- name: Set instance names
  debug:
    msg: "{{ basic_config.name }}-{{ '%03d'|format(item|int) }}"
  register: instance_names
  with_sequence:
    - "start=1 end={{ basic_config.instances_count }}"
  when: instance_created.stdout != ""

- name: Stop instance on google cloud platform
  command: >
    gcloud compute instances stop
    {{ hostvars.localhost.instance_names.results | map(attribute='msg') | list | join(' ') }}

  changed_when: false
  when: '"RUNNING" in instance_created.stdout'
